# -*- coding: utf-8 -*-
"""lidarAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xuzlPU7WYZYBUumE7CmMUllcGaWo-kYi
"""

import matplotlib.pyplot as plt

lines = []
with open('text-3E2FA587C407-1.txt') as f:
    lines = f.readlines()

pairs = []
for i, line in enumerate(lines):
  lines[i] = line.split('\x00',1)[0]
  new_string = ""
  for char in line:
    if char != '\x00' and char != '\n':
      new_string += char
  pairs.append(new_string)

x = []
y = []
for pair in pairs:
    coord = pair.split(",")
    if len(coord) != 2: continue
    print(coord)
    coord_x = None
    coord_y = None
    try:
      coord_x = int(coord[0])
      coord_y = int(coord[1])
    except:
      pass
    if coord_x is not None and coord_y is not None:
      x.append(coord_x)
      y.append(coord_y)

plt.scatter(x, y, alpha=0.5)
plt.show()

